//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stajtakip.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Council
    {
        public int CouncilID { get; set; }
        public Nullable<bool> Approve { get; set; }
        public string CouncilName { get; set; }
        public Nullable<bool> isFilling { get; set; }
        public Nullable<bool> isDeleting { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> SemesterID { get; set; }
    }
}
