//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stajtakip.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class GradeTypeAvarage
    {
        public int GradeTypeAvarageID { get; set; }
        public Nullable<int> GradeCategoryID { get; set; }
        public string GradeCategoryName { get; set; }
        public Nullable<double> GradeTypeAvarage1 { get; set; }
        public Nullable<int> StudentID { get; set; }
        public string StudentName { get; set; }
        public string StudentSurname { get; set; }
        public Nullable<bool> Approve { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> SemesterID { get; set; }
    }
}
