//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stajtakip.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class GradeCategory
    {
        public int GradeCategoryID { get; set; }
        public string GradeName { get; set; }
        public Nullable<int> Percent { get; set; }
        public Nullable<bool> Approve { get; set; }
        public Nullable<bool> isGrading { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public string StartDate { get; set; }
        public string LastDate { get; set; }
        public Nullable<int> SemesterID { get; set; }
    }
}
