//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stajtakip.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class InternInfo
    {
        public int InternID { get; set; }
        public string StudentName { get; set; }
        public string StudentSurname { get; set; }
        public string CompanyName { get; set; }
        public string CompanyAddress { get; set; }
        public string CompanyCity { get; set; }
        public string CompanyPhone { get; set; }
        public string AuthorizedPersonel { get; set; }
        public Nullable<bool> Approve { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<double> Grade { get; set; }
        public Nullable<int> CouncilID { get; set; }
        public Nullable<bool> isDelete { get; set; }
        public Nullable<int> SemesterID { get; set; }
        public Nullable<System.DateTime> DayOfRegistration { get; set; }
    }
}
