//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stajtakip.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class TeacherUserInfo
    {
        public int TeacherID { get; set; }
        [Required(ErrorMessage = "This field cannot be empty!")]
        public string TeacherName { get; set; }
        [Required(ErrorMessage = "This field cannot be empty!")]
        public string TeacherSurname { get; set; }
        [Required(ErrorMessage = "This field cannot be empty!")]
        public string TeacherEmail { get; set; }
        public string TeacherPassword { get; set; }

        public string TeacherRoom { get; set; }
        public Nullable<bool> Approve { get; set; }
        public Nullable<int> CouncilID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        [DisplayName("New Password")]
        [DataType(DataType.Password)]
        public string NewPassword { get; set; }

        [DisplayName("Confirm Password")]
        [DataType(DataType.Password)]
        public string ConfirmPassword { get; set; }
    }
}
